"""add_original_file_fields_to_submission

Revision ID: e24010cbc71d
Revises: 10d5bac50ecd
Create Date: 2025-09-17 14:19:17.597959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24010cbc71d'
down_revision: Union[str, Sequence[str], None] = '10d5bac50ecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('original_file', sa.LargeBinary(), nullable=True, comment='原始文件内容'))
    op.add_column('submissions', sa.Column('file_name', sa.Text(), nullable=True, comment='原始文件名'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'file_name')
    op.drop_column('submissions', 'original_file')
    # ### end Alembic commands ###
